import type { Solution, Challenge, SkillBadge, ImpactKPI, CharterPrinciple } from "./types";

export const BRAND_NAME = "NOVAHEART";
export const TAGLINE = "Human Progress Through Innovation, Education & Action";

export const ROLES = [
  "Innovator",
  "Engineer",
  "Scientist",
  "Designer",
  "Researcher",
  "Educator",
  "Entrepreneur",
  "Contributor",
];

export const BADGE_COLORS = [
  { label: "Cyan", value: "from-cyan-400 to-blue-500" },
  { label: "Emerald", value: "from-emerald-400 to-teal-500" },
  { label: "Violet", value: "from-violet-400 to-purple-500" },
  { label: "Rose", value: "from-rose-400 to-pink-500" },
  { label: "Amber", value: "from-amber-400 to-orange-500" },
  { label: "Indigo", value: "from-indigo-400 to-blue-600" },
];

export const SOLUTIONS: Solution[] = [
  {
    id: "s1",
    title: "OpenCortex",
    description: "Decentralized neural network training platform for collaborative AI research across institutions.",
    category: "AI & ML",
    icon: "BrainCircuit",
    gradient: "from-violet-500 to-purple-600",
    contributors: 342,
    status: "active",
    tech: ["PyTorch", "Rust", "IPFS"],
  },
  {
    id: "s2",
    title: "GreenGrid Protocol",
    description: "Open-source energy distribution optimization for microgrids in developing regions.",
    category: "Energy",
    icon: "Leaf",
    gradient: "from-emerald-500 to-teal-600",
    contributors: 189,
    status: "active",
    tech: ["Go", "React", "MQTT"],
  },
  {
    id: "s3",
    title: "MediChain",
    description: "Privacy-first medical records chain enabling secure cross-border healthcare data sharing.",
    category: "Health",
    icon: "Heart",
    gradient: "from-rose-500 to-pink-600",
    contributors: 276,
    status: "active",
    tech: ["Solidity", "TypeScript", "IPFS"],
  },
  {
    id: "s4",
    title: "EduVerse",
    description: "Immersive VR learning environment for STEM education in underserved communities.",
    category: "Education",
    icon: "GraduationCap",
    gradient: "from-cyan-500 to-blue-600",
    contributors: 154,
    status: "prototype",
    tech: ["Unity", "WebXR", "Node.js"],
  },
  {
    id: "s5",
    title: "BioSense",
    description: "Low-cost biosensor array for real-time environmental toxin detection in water systems.",
    category: "Biotech",
    icon: "Microscope",
    gradient: "from-amber-500 to-orange-600",
    contributors: 98,
    status: "prototype",
    tech: ["Python", "Arduino", "TinyML"],
  },
  {
    id: "s6",
    title: "QuantumMesh",
    description: "Post-quantum encryption mesh network for resilient communications in disaster zones.",
    category: "Security",
    icon: "Shield",
    gradient: "from-indigo-500 to-blue-600",
    contributors: 67,
    status: "idea",
    tech: ["Rust", "WireGuard", "CRYSTALS"],
  },
];

export const CHALLENGES: Challenge[] = [
  {
    id: "c1",
    title: "Ocean Cleanup AI",
    description: "Build a computer vision model to identify and classify microplastic concentrations from satellite imagery.",
    category: "Environment",
    icon: "Globe",
    difficulty: "advanced",
    participants: 127,
    reward: "$50,000",
  },
  {
    id: "c2",
    title: "Rural Connectivity",
    description: "Design a low-bandwidth mesh protocol for reliable internet access in remote mountain villages.",
    category: "Infrastructure",
    icon: "Zap",
    difficulty: "intermediate",
    participants: 84,
    reward: "$35,000",
  },
  {
    id: "c3",
    title: "Crop Disease Detector",
    description: "Create a mobile-first ML tool that identifies crop diseases from leaf photos in real-time.",
    category: "Agriculture",
    icon: "Leaf",
    difficulty: "beginner",
    participants: 203,
    reward: "$20,000",
  },
  {
    id: "c4",
    title: "Universal Translator",
    description: "Develop a real-time sign language translation system using wearable sensors.",
    category: "Accessibility",
    icon: "Heart",
    difficulty: "intermediate",
    participants: 56,
    reward: "$40,000",
  },
  {
    id: "c5",
    title: "Carbon Ledger",
    description: "Build a transparent blockchain ledger for corporate carbon credit tracking and auditing.",
    category: "Climate",
    icon: "Leaf",
    difficulty: "advanced",
    participants: 91,
    reward: "$60,000",
  },
  {
    id: "c6",
    title: "Code for Good",
    description: "Create an open-source platform connecting NGOs with volunteer developers for impact projects.",
    category: "Community",
    icon: "Users",
    difficulty: "beginner",
    participants: 312,
    reward: "$15,000",
  },
];

export const SKILL_BADGES: SkillBadge[] = [
  { id: "b1", name: "Python Pro", category: "Languages", level: 4, icon: "Code", color: "from-blue-400 to-blue-600" },
  { id: "b2", name: "Rustacean", category: "Languages", level: 3, icon: "Code", color: "from-orange-400 to-red-500" },
  { id: "b3", name: "ML Engineer", category: "AI/ML", level: 5, icon: "BrainCircuit", color: "from-violet-400 to-purple-600" },
  { id: "b4", name: "Solidity Dev", category: "Blockchain", level: 3, icon: "Cpu", color: "from-gray-400 to-gray-600" },
  { id: "b5", name: "Biohacker", category: "Biotech", level: 2, icon: "Microscope", color: "from-emerald-400 to-teal-600" },
  { id: "b6", name: "Cloud Architect", category: "Infrastructure", level: 4, icon: "Cloud", color: "from-cyan-400 to-blue-600" },
  { id: "b7", name: "UI/UX Artisan", category: "Design", level: 3, icon: "Palette", color: "from-pink-400 to-rose-600" },
  { id: "b8", name: "Embedded Systems", category: "Hardware", level: 2, icon: "Cpu", color: "from-green-400 to-emerald-600" },
  { id: "b9", name: "Data Scientist", category: "Data", level: 4, icon: "BarChart3", color: "from-indigo-400 to-indigo-600" },
  { id: "b10", name: "DevOps Engineer", category: "Infrastructure", level: 3, icon: "Terminal", color: "from-yellow-400 to-amber-600" },
  { id: "b11", name: "Smart Contract Auditor", category: "Blockchain", level: 2, icon: "Shield", color: "from-red-400 to-red-600" },
  { id: "b12", name: "NLP Specialist", category: "AI/ML", level: 3, icon: "BrainCircuit", color: "from-purple-400 to-violet-600" },
];

export const IMPACT_KPIS: ImpactKPI[] = [
  { id: "k1", label: "Active Innovators", value: 14287, prefix: "", suffix: "+", icon: "Users", gradient: "from-cyan-500 to-blue-600", trend: 12 },
  { id: "k2", label: "Open Source Projects", value: 893, prefix: "", suffix: "", icon: "Code", gradient: "from-emerald-500 to-teal-600", trend: 8 },
  { id: "k3", label: "Communities Reached", value: 245, prefix: "", suffix: "K", icon: "Globe", gradient: "from-violet-500 to-purple-600", trend: 15 },
  { id: "k4", label: "Carbon Offset (tons)", value: 45200, prefix: "", suffix: "+", icon: "Leaf", gradient: "from-green-500 to-emerald-600", trend: 22 },
  { id: "k5", label: "Patents Filed", value: 167, prefix: "", suffix: "", icon: "Award", gradient: "from-amber-500 to-orange-600", trend: 5 },
  { id: "k6", label: "Grant Funding", value: 12.4, prefix: "$", suffix: "M", icon: "Target", gradient: "from-rose-500 to-pink-600", trend: 18 },
];

export const CHARTER_PRINCIPLES: CharterPrinciple[] = [
  {
    id: "p1",
    title: "Open Access Mandate",
    description: "All research and innovations funded through the ecosystem must be published under open-access licenses to ensure maximum global benefit.",
    icon: "BookOpen",
    color: "from-cyan-400 to-blue-500",
  },
  {
    id: "p2",
    title: "Ethical AI Framework",
    description: "Every AI solution must pass bias auditing, explainability checks, and human-rights impact assessments before deployment.",
    icon: "Shield",
    color: "from-emerald-400 to-teal-500",
  },
  {
    id: "p3",
    title: "Community Governance",
    description: "Major decisions affecting the ecosystem are made through transparent, stake-weighted voting by active contributors.",
    icon: "Users",
    color: "from-violet-400 to-purple-500",
  },
  {
    id: "p4",
    title: "Environmental Stewardship",
    description: "All projects must quantify and offset their carbon footprint, with a net-zero mandate by 2030 for the entire ecosystem.",
    icon: "Leaf",
    color: "from-green-400 to-emerald-500",
  },
  {
    id: "p5",
    title: "Digital Sovereignty",
    description: "Every individual retains full ownership and control over their personal data. No data monetization without explicit consent.",
    icon: "Fingerprint",
    color: "from-amber-400 to-orange-500",
  },
  {
    id: "p6",
    title: "Inclusive Design",
    description: "All solutions must be accessible to people with disabilities, support multiple languages, and work on low-bandwidth connections.",
    icon: "Heart",
    color: "from-rose-400 to-pink-500",
  },
];